# Generated by Django 4.2.4 on 2023-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
